name: hypergraph
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults

dependencies:
  # Utilities
  - python=3.9
  - pip
  - numpy=1.26.4
  - scipy
  - pandas
  - matplotlib-base
  - scikit-learn
  - ipykernel
  - jupyter
  - notebook
  - h5py
  - tqdm

  # Deep Learning - PyTorch Ecosystem
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-scatter  # torch_scatter via conda-forge
  - pyg

  # Graph manipulation
  - networkx

 # Bioinformatics
  - anndata
  - scanpy

  - pip:
    - einops
    - lightning
    - optuna

    - matplotlib==3.9.0
    - geovoronoi==0.4.0
    - graphtools==1.5.3
    - optuna==3.6.1

    - pandas==2.0.3
    - phate==1.0.11
    - scprep==1.2.3
   # Utilities and infrastructure
    # - s-gd2==1.8.1
    # - sqlalchemy==2.0.31
    # - tasklogger==1.2.0
    # - wrapt==1.16.0
    # - tqdm>=4.65.0

    # - pygsp==0.5.1
    # - s-gd2==1.8.1
    # - shapely==2.0.4
 
