name: hypergraph-spatial-cpu
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly  # Remove this line if you want GPU support
  - pyg
  - pytorch-sparse
  - pytorch-scatter
  - pytorch-cluster
  - einops
  - pytorch-lightning
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - ipykernel
  - jupyter
  - notebook
  - h5py
  - tqdm
  - networkx
  - anndata
  - scanpy
  - pip
  - pip:
    - torch-geometric
    - geovoronoi
    - graphtools==1.5.3