name: hypergraph
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.26.4
  - scipy
  - pandas
  - matplotlib-base
  - networkx
  - scikit-learn
  - h5py
  - pytorch
  - torchvision
  - torchaudio
  - pytorch
  - torchvision
  - torchaudio
  - pyg
  - ipykernel
  - jupyter
  - notebook
  - anndata
  - scanpy
  - tqdm
  - pip:
    - einops
    - optuna
    - dhg
    - matplotlib==3.9.0
    - dhg==0.9.4
    - geovoronoi==0.4.0
    - graphtools==1.5.3
    - optuna==3.6.1
    - pandas==2.0.3
    - phate==1.0.11
    - pygsp==0.5.1
    - s-gd2==1.8.1
    - scprep==1.2.3
    - shapely==2.0.4
    - sqlalchemy==2.0.31
    - tasklogger==1.2.0
    - wrapt==1.16.0
    - tqdm>=4.65.0
    - lightning