name: hypergraph
channels:
  - pytorch
  - pyg
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - pyg
  - einops
  - pytorch-lightning
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - ipykernel
  - jupyter
  - notebook
  - h5py
  - tqdm
  - networkx
  - anndata
  - scanpy
  - pip:
    - torch
    - torchvision
    - torchaudio
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-geometric
    - geovoronoi
    - graphtools==1.5.3