name: hypergraph-cuda
channels:
  - pytorch
  - pyg
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - pip
  - einops
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - ipykernel
  - jupyter
  - notebook
  - h5py
  - tqdm
  - networkx
  - anndata
  - scanpy
  - pytest
  - pip:
    - geovoronoi