[project]
name = "hypergraph-wavelets"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anndata",
    "einops",
    "graphtools",
    "matplotlib",
    "networkx",
    "numpy",
    "opencv-python",
    "pandas",
    "phate",
    "pyarrow",
    "pytorch-lightning",
    "scanpy",
    "scikit-learn",
    "scipy",
    "torch",
    "torch-geometric",
    "torchmetrics",
    "torchvision",
    "tqdm",
]

[project.optional-dependencies]
dev = [
    "ipykernel",
    "jupyter",
    "jupyterlab",
]